### ISSUE TITLE
QMMM: nwchem - options

### ISSUE THREAD

**Issue by mbarbry** [votca/xtp#143]
It seems that to be able to use nwchem with QMMM, the option

    set bq background

must be present. However, if the option is missing, no error messages are printed and the program get stuck into a while loop (it seems). At least nwchem calculations fail since the molecule geometry is not written in the input file.

A line checking if `_write_charges` is true would be necessary.

**Comment by JensWehner** [comment]
which branch?

**Comment by mbarbry** [comment]
I'm in master branch.
The problem come from the line

    if (_write_charges) {
         qmatoms = orbitals_guess->QMAtoms();
    } else {
        QMMInterface qmmface;
        qmatoms = qmmface.Convert(segments);
    }

in `qmpackages/nwchem.cc`

**Comment by JensWehner** [comment]
It is fixed in tutorial-fixes

**Comment by mbarbry** [comment]
ok, I will give it a try!

**Comment by mbarbry** [comment]
With the branch tutorial-fixes, there is still some error message missing. In my test, somehow, there is no background charge (probably caused by some issue with previous jobs), then nwchem fails with the error

    bq_input: max_nbq                   0

However, this is still not visible from the xtp side which continues to run.

**Comment by mbarbry** [comment]
It writes some option related to bp, however `set bq background` is not present.
[system.nw.txt](https://github.com/votca/xtp/files/2253412/system.nw.txt)

**Comment by JensWehner** [comment]
okay let me check, give me 30 min

**Comment by JensWehner** [comment]
Did you have it in there before?

**Comment by mbarbry** [comment]
The options?
In the master branch there were written only if I added `set bq background` to the options manually in dftpackage.xml, otherwise, nothing was written, not even the geometry of the molecule.

**Comment by JensWehner** [comment]
Yeah, I tried to fix it in tutorials_fix if you set ``set bq background`` manually there it should work just fine.

**Comment by mbarbry** [comment]
In my particular case, it does not work because the total number of charge is null. Thus nwchem failed to run since it expects some charges

    0:bq_input: max_nbq:Received an Error in Communication

I think then, that an error should be return if the number of charges is null.
In `qmpackages/nwchem.cc` we have the line 

    int numberofcharges=WriteBackgroundCharges(_crg_file);

it is then easy to add a check,

    if (numberofcharges == 0.0) {
        die("no charge in the background, check your inputs, or whatever other message")
    }

By the way, any clue why I don't have charges in my test? It is difficult to understand why from the code.

**Comment by JensWehner** [comment]
Good question. Are your cutoffs to small?

**Comment by JensWehner** [comment]
Ahh okay. I will add this exception to the code

**Comment by mbarbry** [comment]
No, I took quite a large cutoff and saw that quite a lot of molecules were participating to the background charge. I think it is because of my ab initio calculations. When looking to the mps file, I see no charge.
[segMethane_e.mps.txt](https://github.com/votca/xtp/files/2253738/segMethane_e.mps.txt)

**Comment by mbarbry** [comment]
I think the partial charge reader for nwchem is outdated or I did not run my ab initio calculations correctly and I don't get the line expected by the parser ....

**Comment by JensWehner** [comment]
yes the mps file has no charge, so nothing is written out.

It should have an error. How did you make the mps file?

**Comment by mbarbry** [comment]
I used log2mps to generate the mps file.
but I found out why It did not read the charges, it is because log2mps is expecting the string EPS in the nwchem log. If this string is absent then no charges are read. I have to modify thus my nwchem calculations in order that they perform electrostatic potential calculations.

**Comment by JensWehner** [comment]
Yes, log2mps cannot read charges without charges being calculated.

**Comment by JensWehner** [comment]
This is really valuable for us. You have at least discovered 3 edge cases so far.

**Comment by mbarbry** [comment]
Ja, I guessed that having a someone testing the code is nice for you to improve votca, for me it is a painful path  :D

**Comment by JensWehner** [comment]
sorry. I do apologize.

**Comment by mbarbry** [comment]
No issues, I know what is it do develop scientific software

**Comment by baumeier** [comment]
> Ja, I guessed that having a someone testing the code is nice for you to improve votca, for me it is a painful path :D

@mbarbry  Just chiming in to say that it is really helpful. Especially with the ways the different qmpackages work, and nwchem not being our "work horse", there are a bunch of things we don't easily spot.

**Comment by mbarbry** [comment]
I'm glad to help!
I found another bug. I'm getting a segmentation fault in `gwbse/sigma.cc`, routine `Sigma::X_diag`.

It is concerning the loop 

    for (unsigned i_occ = 0; i_occ <= _homo; i_occ++)

In my case, `_homo = - 1` (probably because I'm not initializing my jobs correctly). Thus, the loop will never finish, and we finish to get a segfault when `i_occ` is too large.

You should probably had a test there,

    if (_homo < 0) die("Error message")

**Comment by mbarbry** [comment]
or just using an `int` instead of an `unsigned` for `i_occ` would avoid entering into the loop. But my knowledge of C++ is rather limited, you probably know better how to handle such situation.

**Comment by mbarbry** [comment]
The issue is that in this particular calculation, the number of electrons detected by xtp is 0. This is because of the orbitals file converted with the mov2asc executable. The number of electrons is obtained by summing over when a number in this file is equal to 2. `qmpackages/nwchem.cc` 

    _input_file >> _occ[ _imo ];
    if (_occ[ _imo ] == 2.0) {
        _number_of_electrons++;
    }

Somehow in my file, I have 1 instead of 2, thus the number of electrons is null. Any clue why?

**Comment by mbarbry** [comment]
Do you know why the number of electron is read from the molecular orbitals file in nwchem?
It is directly accessible from the main output.

    No. of electrons :    10
    Alpha electrons :     5
    Beta electrons :     5

[system.log](https://github.com/votca/xtp/files/2256820/system.log)

**Comment by JensWehner** [comment]
Yes, one flaw of votca is that is was originally designed for closed shell molecules. E.g. alpha electrons are only counted. It is flawed

**Comment by mbarbry** [comment]
Ok, I just opened a pull request. I think there is a bug in the nwchem parser.

**Comment by baumeier** [comment]
What I find odd is that this part has always worked for closed-shell systems since 5 years ago for the calculation of transfer integrals. Which version of nwchem does this happen with? Maybe they changed the structure of the file, putting occ=1 and having alpha and beta electrons separately.

**Comment by mbarbry** [comment]
The thing is that to do calculations with charges, we need to do open shell calculations? 
Or maybe I did not understand correctly how to do calculations with charges with nwchem.

**Comment by baumeier** [comment]
Do you want to do GW on a charged system? That is currently not implemented, but on our list.

**Comment by mbarbry** [comment]
No, not for the moment at least. This may explain why it is not working. 
I was getting an error running GW with nwchem, I was thinking it was because it was running DFT with charged systems. I see a folder created by xtp xjob_2_1:segmethane:e which run DFT with a charge. Then, to perform this calculation, nwchem uses openshell, and then the nwchem parser does not manage to gets the number of electrons.

[system.nw.txt](https://github.com/votca/xtp/files/2257390/system.nw.txt)

**Comment by baumeier** [comment]
Yeah, if you run GW on open-shell systems, this is sort-of expected behavior. In the sense that it should fail, ideally with a check before.

Now, why it is doing this inside xjob_2_1:segmethane:e at all with GW, is something I don't really understand. We can run plain DFT in QMMM with nwchem also for charged molecules but it relies on nwchem's internal espfit procedure. Then the parser should only read energy and esp charges, or at least only use those.

**Comment by baumeier** [comment]
OK, you must have jobs in the qmmm.jobs file with segmethane:e and segmethane:h or something, while at the same time a <gwbse> section in qmmm.xml options files. That's at least how I can rationalize that this combination can occur.

**Comment by JensWehner** [comment]
The problem is probably a mismatch between the tags in qmmm and gwbse

**Comment by mbarbry** [comment]
A solution to avoid issues in reading the number of electron with nwchem would be to get them directly from the main output instead of the molecular orbitals. They are written in plain text so no rooms for mistakes.

    No. of atoms     :     5
    No. of electrons :    11
    Alpha electrons :     6
    Beta electrons :     5
    Charge           :    -1
    Spin multiplicity:     2

**Comment by baumeier** [comment]
That would seem a sensible option to me. Plus for the moment that if the parser tries to read MOs with occ=1, throw an error - until we have a data structure to read alpha and beta orbitals into separately.

**Comment by JensWehner** [comment]
I close this issue, as it basically pertains to the larger issue of spin. THe background charge problem was fixed
